fn main() -> Result<(), std::io::Error> {
    println!("Hello, world!");
    Ok(())
}
